general.import = [".~/.config/alacritty/dracula.toml"]

[terminal.shell]
# program = "/bin/bash"
program = "/usr/bin/fish"

# args = ["-l"]

[env]
WINIT_X11_SCALE_FACTOR = "1.5"
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[mouse]


bindings = [
  { mouse = "Right", action = "ExpandSelection" },
  { mouse = "Right", mods = "Control", action = "ExpandSelection" },
  { mouse = "Middle", mode = "~Vi", action = "PasteSelection" },
]
#
# double_click= { threshold= 300 }
# triple_click= { threshold= 300 }

[keyboard]

bindings = [
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  # , { key= "L",               mods= "Control",                        action= "ClearLogNotice" }
  { key = "L", mods = "Control", mode = "Vi|Search", chars = "x0c" },
  { key = "PageUp", mods = "Shift", mode = "Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", mode = "Alt", action = "ScrollToTop" },
  { key = "End", mods = "Shift", mode = "Alt", action = "ScrollToBottom" },
  # (Windows, Linux, and BSD only)
  { key = "V", mods = "Control|Shift", mode = "Vi", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "F", mods = "Control|Shift", mode = "Search", action = "SearchForward" },
  { key = "B", mods = "Control|Shift", mode = "Search", action = "SearchBackward" },
  { key = "C", mods = "Control|Shift", mode = "Vi|Search", action = "ClearSelection" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Control", action = "DecreaseFontSize" },
  # Claude 
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]
